skip_train: true
skip_test: true
skip_video: false
iteration: 14000

model_params:
  sh_degree: 3
  source_path: "/home/ubuntu/datasets/dynerf/cook_spinach"
  model_path: "./output/dynerf/cook_spinach_mytrain96"
  # source_path: "/home/ubuntu/datasets/dynerf/cook_spinach/segments/2s_05"
  # model_path: "./output/dynerf/cook_spinach_2s05"
  images: "images"
  resolution: -1
  white_background: true
  data_device: "cuda"
  eval: True
  render_process: False
  add_points: False
  extension: ".png"
  llffhold: 8

pipeline_params:
  convert_SHs_python: false
  compute_cov3D_python: false
  debug: false
  port: 6017
  expname: "dynerf/cook_spinach_mytrain"
  test_iterations: [3000, 7000, 14000]
  save_iterations: [14000]
  checkpoint_iterations: []
  start_checkpoint: null

model_hidden_params:
  net_width: 128
  timebase_pe: 4
  defor_depth: 0
  posebase_pe: 10
  scale_rotation_pe: 2
  opacity_pe: 2
  timenet_width: 64
  timenet_output: 32
  bounds: 1.6
  plane_tv_weight: 0.0002
  time_smoothness_weight: 0.001
  l1_time_planes: 0.0001
  kplanes_config: {
    'grid_dimensions': 2,
    'input_coordinate_dim': 4,
    'output_coordinate_dim': 16,
    'resolution': [96, 96, 96, 150]
  }
  multires: [1, 2]
  no_dx: False
  no_grid: False
  no_ds: False
  no_dr: False
  no_do: False
  no_dshs: False
  empty_voxel: False
  grid_pe: 0
  static_mlp: False
  apply_rotation: False
  
optimization_params:
  dataloader: True
  zerostamp_init: False
  custom_sampler: null
  iterations: 14000
  coarse_iterations: 3000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 20000
  deformation_lr_init: 0.00016
  deformation_lr_final: 0.000016
  deformation_lr_delay_mult: 0.01
  grid_lr_init: 0.0016
  grid_lr_final: 0.00016
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0
  lambda_lpips: 0
  weight_constraint_init: 1
  weight_constraint_after: 0.2
  weight_decay_iteration: 5000
  opacity_reset_interval: 60000
  densification_interval: 100
  densify_from_iter: 500
  densify_until_iter: 10000
  densify_grad_threshold_coarse: 0.0002
  densify_grad_threshold_fine_init: 0.0002
  densify_grad_threshold_after: 0.0002
  pruning_from_iter: 500
  pruning_interval: 100
  opacity_threshold_coarse: 0.005
  opacity_threshold_fine_init: 0.005
  opacity_threshold_fine_after: 0.005
  batch_size: 1
  add_point: False